mongodb:
  URL: "mongodb://admin:123456@localhost:27017/?authSource=admin&replicaSet=rs0"
  MONGO_INITDB_ROOT_USERNAME: "admin"
  MONGO_INITDB_ROOT_PASSWORD: "123456"
  MONGO_INITDB_DATABASE: "stellux"
  MONGO_USERNAME: "codepzj"
  MONGO_PASSWORD: "123456"

server:
  PORT: 9001
